#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage:
  scripts/validate_fedora_rpm_review_candidate.sh --evidence-dir <dir> [--builder rpmbuild|mock] [--mock-config <name>]

Validates a Fedora RPM review-candidate evidence directory generated by
prepare_fedora_rpm_review_candidate.sh. The build consumes only the declared
source, Cargo vendor, and npm cache archives from that evidence directory.

The default builder is rpmbuild. The mock builder requires mock to be installed
and rebuilds the generated source RPM in the selected mock configuration.
USAGE
}

evidence_dir=""
builder="rpmbuild"
mock_config=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --evidence-dir)
      evidence_dir="${2:-}"
      shift 2
      ;;
    --builder)
      builder="${2:-}"
      shift 2
      ;;
    --mock-config)
      mock_config="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ -z "$evidence_dir" ]]; then
  echo "Missing required --evidence-dir <dir>" >&2
  usage >&2
  exit 2
fi

case "$builder" in
  rpmbuild|mock) ;;
  *)
    echo "Unsupported --builder: $builder" >&2
    usage >&2
    exit 2
    ;;
esac

repo_root="$(git rev-parse --show-toplevel)"
cd "$repo_root"

required_commands=(git rpm rpmbuild sha256sum tar)
if [[ "$builder" == "mock" ]]; then
  required_commands+=(mock)
fi

for command_name in "${required_commands[@]}"; do
  if ! command -v "$command_name" >/dev/null 2>&1; then
    echo "Missing required command: $command_name" >&2
    exit 1
  fi
done

if [[ -n "$(git status --porcelain)" ]]; then
  echo "Working tree must be clean before validating release evidence." >&2
  exit 1
fi

evidence_dir="$(cd "$evidence_dir" && pwd)"
artifact_dir="$evidence_dir/artifacts"
manifest_dir="$evidence_dir/manifests"
checksum_file="$evidence_dir/SHA256SUMS"

for required_path in "$artifact_dir" "$manifest_dir" "$checksum_file" "$evidence_dir/EVIDENCE.md"; do
  if [[ ! -e "$required_path" ]]; then
    echo "Missing required evidence path: $required_path" >&2
    exit 1
  fi
done

(
  cd "$evidence_dir"
  sha256sum --check SHA256SUMS
)

spec_file="$repo_root/packaging/fedora/redshield-architect-workbench.spec"
version="$(awk '/^Version:/ { print $2; exit }' "$spec_file")"
source_archive="$artifact_dir/redshield-architect-$version.tar.gz"
cargo_vendor_archive="$artifact_dir/redshield-architect-$version-cargo-vendor.tar.gz"
npm_cache_archive="$artifact_dir/redshield-architect-$version-npm-cache.tar.gz"
cargo_inventory="$manifest_dir/cargo-dependency-inventory.tsv"
npm_inventory="$manifest_dir/npm-dependency-inventory.tsv"

for required_path in \
  "$source_archive" \
  "$cargo_vendor_archive" \
  "$npm_cache_archive" \
  "$cargo_inventory" \
  "$npm_inventory"; do
  if [[ ! -f "$required_path" ]]; then
    echo "Missing required evidence file: $required_path" >&2
    exit 1
  fi
done

validation_root="$repo_root/target/fedora-rpm-review-validation/$(basename "$evidence_dir")"
topdir="$validation_root/rpmbuild"
result_dir="$validation_root/results"
rm -rf "$validation_root"
mkdir -p "$topdir"/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS} "$result_dir"

cp "$source_archive" "$topdir/SOURCES/"
cp "$cargo_vendor_archive" "$topdir/SOURCES/"
cp "$npm_cache_archive" "$topdir/SOURCES/"
cp "$spec_file" "$topdir/SPECS/"

rpmbuild \
  --define "_topdir $topdir" \
  --define "_smp_mflags -j$(nproc)" \
  --with offline_sources \
  -bs "$topdir/SPECS/$(basename "$spec_file")"

srpm="$(find "$topdir/SRPMS" -type f -name '*.src.rpm' | sort | tail -n 1)"
if [[ -z "$srpm" ]]; then
  echo "Source RPM was not created." >&2
  exit 1
fi

if [[ "$builder" == "mock" ]]; then
  mock_args=(--rebuild --resultdir "$result_dir")
  if [[ -n "$mock_config" ]]; then
    mock_args+=(--root "$mock_config")
  fi
  mock "${mock_args[@]}" "$srpm"
else
  rpmbuild \
    --define "_topdir $topdir" \
    --define "_smp_mflags -j$(nproc)" \
    --with offline_sources \
    --rebuild "$srpm"

  find "$topdir/RPMS" "$topdir/SRPMS" -type f \( -name '*.rpm' -o -name '*.src.rpm' \) \
    -exec cp {} "$result_dir/" \;
fi

{
  echo "# Fedora RPM Offline Validation"
  echo
  echo "- Evidence directory: \`$evidence_dir\`"
  echo "- Builder: \`$builder\`"
  if [[ -n "$mock_config" ]]; then
    echo "- Mock config: \`$mock_config\`"
  fi
  echo "- Version: \`$version\`"
  echo "- Generated: \`$(date -u +%Y-%m-%dT%H:%M:%SZ)\`"
  echo
  echo "## Declared Inputs"
  echo
  echo "- \`$(basename "$source_archive")\`"
  echo "- \`$(basename "$cargo_vendor_archive")\`"
  echo "- \`$(basename "$npm_cache_archive")\`"
  echo "- \`$(basename "$cargo_inventory")\`"
  echo "- \`$(basename "$npm_inventory")\`"
  echo
  echo "## Results"
  echo
  find "$result_dir" -maxdepth 1 -type f | sort | while read -r result; do
    echo "- \`$(basename "$result")\`"
  done
} > "$validation_root/OFFLINE_VALIDATION.md"

echo "Fedora RPM offline validation completed with $builder."
echo "Results: $result_dir"
echo "Evidence: $validation_root/OFFLINE_VALIDATION.md"
